services:
  - type: web
    name: acme-product-import-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --worker-class eventlet
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        value: zAkeQKH+Hb/Xc1aK32PmSgLiwf5P9IBCm0HibZRjUr8=
      - key: SUPABASE_URL
        value: https://bhyrldeuwxmtaebjpcmu.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoeXJsZGV1d3htdGFlYmpwY211Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NDYyNjcsImV4cCI6MjA3OTEyMjI2N30.KBqsUxIBuM_SwmKB42q6z71UYMexe3rrnA06KjI3610
      - key: DATABASE_URL
        value: postgresql+psycopg2://postgres:yQssSttRghFbuthG@db.bhyrldeuwxmtaebjpcmu.supabase.co:5432/postgres?sslmode=require
      - key: REDIS_URL
        fromService:
          type: redis
          name: acme-redis
          property: connectionString

  - type: worker
    name: acme-product-import-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.celery worker --loglevel=info --concurrency=1 --pool=solo
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        value: zAkeQKH+Hb/Xc1aK32PmSgLiwf5P9IBCm0HibZRjUr8=
      - key: SUPABASE_URL
        value: https://bhyrldeuwxmtaebjpcmu.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoeXJsZGV1d3htdGFlYmpwY211Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NDYyNjcsImV4cCI6MjA3OTEyMjI2N30.KBqsUxIBuM_SwmKB42q6z71UYMexe3rrnA06KjI3610
      - key: DATABASE_URL
        value: postgresql+psycopg2://postgres:yQssSttRghFbuthG@db.bhyrldeuwxmtaebjpcmu.supabase.co:5432/postgres?sslmode=require
      - key: REDIS_URL
        fromService:
          type: redis
          name: acme-redis
          property: connectionString

databases:
  - name: acme-redis
    plan: free